// <auto-generated />
using GuliERP.DocumentKernel.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GuliERP.DocumentKernel.Infrastructure.Migrations
{
    /// <summary>
    /// Designer metadata for <c>DOCKERNEL001_InitializeDocKernelSchema</c>.
    /// Standard EF Core pattern: the [DbContext] + [Migration]
    /// attributes enable <c>dotnet ef migrations list</c> and
    /// <c>dotnet ef database update</c> to discover the migration.
    /// </summary>
    [DbContext(typeof(DocumentKernelDbContext))]
    [Migration("20260821000000_DOCKERNEL001_InitializeDocKernelSchema")]
    partial class DOCKERNEL001_InitializeDocKernelSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("doc_kernel")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Canonical HiLo sequence (owned by Identity IDGEN001).
            modelBuilder.HasSequence("gulierp_hilo_sequence", "identity")
                .IncrementsBy(10);

            modelBuilder.Entity("GuliERP.DocumentKernel.Domain.Entities.DocumentNumberCounter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("Id"), "gulierp_hilo_sequence", "identity");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<long>("LastValue")
                        .HasColumnType("bigint");

                    b.Property<string>("LastGeneratedDocumentNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<int>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TenantId", "CompanyId", "DocumentType", "PeriodKey" }, "ux_doc_number_counter_scope")
                        .IsUnique();

                    b.ToTable("document_number_counter", "doc_kernel");
                });

            modelBuilder.Entity("GuliERP.DocumentKernel.Domain.Entities.DocumentNumberIdempotency", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GeneratedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("GeneratedDocumentNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("IdempotencyKey");

                    b.HasIndex(new[] { "TenantId", "DocumentType", "IdempotencyKey" }, "ix_doc_number_idempotency_lookup");

                    b.ToTable("document_number_idempotency", "doc_kernel");
                });
#pragma warning restore 612, 618
        }
    }
}
