<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>GuliERP.Foundation.Tests</RootNamespace>
    <AssemblyName>GuliERP.Foundation.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\modules\foundation\GuliERP.Foundation\GuliERP.Foundation.csproj" />
  </ItemGroup>
</Project>
