<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\foundation\GuliERP.Foundation\GuliERP.Foundation.csproj" />
    <ProjectReference Include="..\..\identity\GuliERP.Identity.Application\GuliERP.Identity.Application.csproj" />
    <ProjectReference Include="..\..\identity\GuliERP.Identity.Infrastructure\GuliERP.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\mdm\GuliERP.Mdm.Domain\GuliERP.Mdm.Domain.csproj" />
    <ProjectReference Include="..\..\mdm\GuliERP.Mdm.Infrastructure\GuliERP.Mdm.Infrastructure.csproj" />
    <ProjectReference Include="..\..\document-kernel\GuliERP.DocumentKernel.Application\GuliERP.DocumentKernel.Application.csproj" />
    <ProjectReference Include="..\GuliERP.Sales.Application\GuliERP.Sales.Application.csproj" />
    <ProjectReference Include="..\GuliERP.Sales.Domain\GuliERP.Sales.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
