<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>GuliERP.Mdm.Domain</RootNamespace>
    <AssemblyName>GuliERP.Mdm.Domain</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\foundation\GuliERP.Foundation\GuliERP.Foundation.csproj" />
  </ItemGroup>
</Project>
