// <auto-generated />
using GuliERP.Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GuliERP.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260822090000_G2EnterpriseOrganizationFoundation")]
    partial class G2EnterpriseOrganizationFoundation
    {
    }
}
