<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>GuliERP.Mdm.Bootstrap.Tests</RootNamespace>
    <AssemblyName>GuliERP.Mdm.Bootstrap.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Xunit.SkippableFact" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\tools\GuliERP.Mdm.Bootstrap\GuliERP.Mdm.Bootstrap.csproj" />
  </ItemGroup>

</Project>
